### PR TITLE
restructured cogsys examination instance and related files

### PR DESCRIPTION
**Pull request by henryotunuya**
@javier-romero 
- cogsys examinations instance put in `/instances/cogsys` as `cogsys-examinations.lp`.
- general cogsys examinations constraints put in `/instances/cogsys` as `cogsys-examinations-constraint.lp`.
- `test-09` in `/tests` contains one special cogsys examinations constraint.

### CODE REVIEW

**Comment by javier-romero** [comment]
Hi Henry, 

just two things:
- please check if we should change anything in the main README file at the root of the repo
- please check also if we should change anything in the README inside the tests folder (I think the tests I did no longer run)

**Comment by henryotunuya** [comment]
> Hi Henry,
> 
> just two things:
> 
> * please check if we should change anything in the main README file at the root of the repo
> * please check also if we should change anything in the README inside the tests folder (I think the tests I did no longer run)

Hi @javier-romero,

I have made the requested changes. Please take a look.
I completely forgot about the READMEs.

**Comment by javier-romero** [comment]
Thanks Henry! Just one little thing, and I know this is nitpicking, but to keep the naming homogeneus: could you please rename the file (also in the README) `cogsys-examinations-constraint.lp` to `cogsys-examinations-constraints.lp`?

**Comment by henryotunuya** [comment]
> Thanks Henry! Just one little thing, and I know this is nitpicking, but to keep the naming homogeneus: could you please rename the file (also in the README) `cogsys-examinations-constraint.lp` to `cogsys-examinations-constraints.lp`?

Hi @javier-romero ,

Change made.

**Comment by javier-romero** [comment]
Nice, thank you @henryotunuya!

**Pull request merged**
