### PR TITLE
uncommented commented line, corrected 'im1' and 'msc1', and removed 'n' semester constant

### PR DESCRIPTION
**Pull request by henryotunuya**

### CODE REVIEW

**Comment by javier-romero** [comment]
Thank you @henryotunuya!

Two questions:

1. Why did you change `im` to `im1`? 
2. Why did you eliminate the constant `n`? It is usually handy to define the constants in the instance, and then possibly modify them using the command line.

**Comment by henryotunuya** [comment]
Hi @javier-romero,

> 1. Why did you change `im` to `im1`?

In the paper we have it as `im` not `im1`.
In the study regulation document it is actually `im1` but the `1` was not added in the paper (maybe an oversight)


> 2. Why did you eliminate the constant `n`? It is usually handy to define the constants in the instance, and then possibly modify them using the command line.

I removed it because we did not have it in the "original" [instance](https://github.com/krr-up/study-reg-paper/blob/master/listings/examinations/cogsys.lp) .

Of course we can include it, but maybe it was not there because you set the constant `n` in the [command line](https://github.com/krr-up/study-reg-paper/tree/master/listings/examinations#readme) for the tests.

**Comment by javier-romero** [comment]
Ok, but then I suggest to undo those changes:

1. I would keep the `im`, since in this repo I think it is more important to be consistent with the paper than with the study regulation document.
2. I would keep the constant `n` as this is the usual approach in ASP.

Once you do that, we can merge.

**Comment by henryotunuya** [comment]
Okay, the change has been made.

**Pull request merged**
